# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
                ('award_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('entry_created', models.DateTimeField(auto_now_add=True)),
                ('entry_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('user_rating', models.IntegerField(default=-1)),
                ('notes', models.TextField()),
                ('format', models.SmallIntegerField(choices=[(0, 'paper'), (1, 'ebook'), (2, 'audiobook')])),
                ('focus', models.SmallIntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')])),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('creator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Creator')),
            ],
            bases=('books.creator',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('creativework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.CreativeWork')),
                ('pub_year', models.DateField(verbose_name='year published')),
                ('have_read', models.BooleanField()),
                ('status', models.SmallIntegerField(choices=[(0, 'not reading'), (1, 'reading'), (2, 'dormant')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
            ],
            bases=('books.creativework',),
        ),
        migrations.AddField(
            model_name='rating',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.CreativeWork'),
        ),
        migrations.AddField(
            model_name='creativework',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='award',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.CreativeWork'),
        ),
        migrations.AddField(
            model_name='reading',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
