# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160417_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='user_rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'not reading'), (1, 'reading'), (2, 'dormant'), (3, 'abandoned')], default=0),
        ),
    ]
